### ISSUE TITLE
yay builds fail

### ISSUE THREAD

**Issue by jerinphilip** [XapaJIaMnu/translateLocally#106]
https://github.com/browsermt/marian-dev/issues/95

**Comment by XapaJIaMnu** [comment]
That should be fixed in upstream aur: https://aur.archlinux.org/packages/translatelocally-git 
The PKGBUILD does `CC=clang CXX=clang++ cmake`. Fixing that in marian is more complicated and I don't know where to start as GCC is tripping on its own instrinsics:

**Comment by jerinphilip** [comment]
> Do you still have trouble building it with the PKGBUILD from aur.archlinux.org?

My local builds now work, also firefox-translations using translateLocally.
