### ISSUE TITLE
Native Messaging through Firefox launches GUI

### ISSUE THREAD

**Issue by jerinphilip** [XapaJIaMnu/translateLocally#110]
I have translateLocally instances spawned all over when trying to use benchmark. 

```
[jerin@thinkpad bergamot-translator]$ ps ax | grep translateLocally
 105888 ?        Sl     0:01 /usr/bin/translateLocally /home/jerin/.mozilla/native-messaging-hosts/translatelocally.json {c9cdf885-0431-4eed-8e18-967b1758c951}
 106231 ?        Sl     0:01 /usr/bin/translateLocally /home/jerin/.mozilla/native-messaging-hosts/translatelocally.json {c9cdf885-0431-4eed-8e18-967b1758c951}
 107096 pts/0    S+     0:00 grep translateLocally
```

https://github.com/XapaJIaMnu/translateLocally/blob/cd02f391a987824614e34c6b8d6c8aca0eb06511/src/cli/CLIParsing.h#L52-L58

![image](https://user-images.githubusercontent.com/727292/177637414-3b8c3e61-526d-46de-800a-4fcff9c72630.png)

**Comment by jelmervdl** [comment]
That's a bug in the benchmarking code in the extension. It should close the connection to the native messaging client.

It is also expected that you'd have multiple instances open on the benchmark page as it uses its own instance, not the one that the add-on uses for translating webpages. Under normal circumstances you'd only have a single instance running (at least, only one started by Firefox.)
