### ISSUE TITLE
NativeMessaging on Windows broken

### ISSUE THREAD

**Issue by jelmervdl** [XapaJIaMnu/translateLocally#111]
TranslateLocally starts correctly, but never responds to any input. Then, once stdin/stdout disconnect (I'm trying this from python) it starts running at 50% cpu eating memory. As if it starts reading random stuff, never processing it. Stopping IDLE does not kill the translateLocally instance it started, I manually had to stop them through Task manager.

Both 2019 and 2022 windows builds do this.

**Comment by jelmervdl** [comment]
I've tried it with and without.

Reverting back to using std::cin & std::cout works. It's as if the C++ runtime does something interesting under the hood, or QFile is not up for the task.

I'm planning on reverting back to std::cin/cout, and then trying to figure out why that doesn't work on Linux. (To be honest, mostly because I'd rather debug with Ubuntu & gcc than with Visual Studio…)

**Comment by jelmervdl** [comment]
I'm suspecting the `std::ios_base::sync_with_stdio(false);` call in the NativeMsgIface constructor.

I understand that this could be related, but I don't yet understand why. As far as I'm aware, we're never using C-style APIs on stdout so why does synchronisation of buffers matter?

**Comment by jelmervdl** [comment]
I might have found something: adding `std::cin.tie(NULL)` works.

As far as I understand, `std::cin` is normally tied to cout in such a way that cout is automatically flushed before cin is read. We read and write concurrently from different threads. I can understand how that might cause a race condition somewhere where the cout buffer is flushed while being written to.

**Comment by XapaJIaMnu** [comment]
I vaguely remember doing that but not sure if it was for performance reasons or because of Windows support.

**Comment by XapaJIaMnu** [comment]
I vaguely remember doing that but not sure if it was for performance reasons or because of Windows support.

**Comment by jelmervdl** [comment]
Neither `sync_with_stdio(false)` nor `std::cin.tie(NULL)` seem relevant for Windows compatibility. I think that is an issue related to using QFile with C style file descriptors for streams on Windows. While I was figuring out how that should work, I did notice bug reports around it which makes me believe that it isn't exactly common or well tested.

I've seen `sync_with_stdio(false)` being used for performance reasons. And in the translateLocally use case it would make sense to me to use it. I'd never seen the `std::cin.tie(NULL)` one before today. But reading up on what it does, it makes sense to untie them in translateLocally as well.

I looked up the documentation on sync_with_stdio:

> Unless `std::ios_base::sync_with_stdio(false)` has been issued, it is safe to concurrently access these objects [`cin`, `cout`, red.] from multiple threads for both formatted and unformatted output.

`std::basic_ios::tie()` is pretty simple:

> Manages the tied stream. A tied stream is an output stream which is synchronized with the sequence controlled by the stream buffer (`rdbuf()`), that is, `flush()` is called on the tied stream before any input/output operation on `*this`.

So it now makes more sense to me that if the implementation of that synchronisation just calls `flush()`, and that `flush()` call is not thread-safe as far as I can tell, resulting in the buffer being flushed multiple times? That would explain what I've been seeing.

**Comment by jelmervdl** [comment]
I just tested the latest build on Windows again, and it works there. I've tested it on Ubuntu as well and have not seen any issues. I've asked Jerin whether he can try to reproduce the initial issue #109 as well, but I have high hopes it will be fixed for him as well.
