### ISSUE TITLE
Translation in progress indicator

### ISSUE THREAD

**Issue by jelmervdl** [XapaJIaMnu/translateLocally#13]
Right now the translation output text gets replaced by some text indicating translation is in progress. With the translate-as-you-type this doesn't work very well as this text often gets replaced by a (stale) translation almost as soon as it first appeared. (Notable exception: at start-up, when Marian is still loading the model, when there is a long wait.)

I suggest adding a loading indicator that doesn't also use the translation output text field so these two don't collide.

I had a couple of options in mind. Using an earlier mock-up for some more quick & dirty mock-ups:
## A spinner overlay
![spinner](https://user-images.githubusercontent.com/198639/117479358-248aef80-af58-11eb-9194-b3f0959637f0.png)  

- 👍Reasonably simple to implement
- 👍Familiar
- ❌No native Qt element
- ❌Obscures translation output

## Spinner in toolbar
![toolbar-spinner](https://user-images.githubusercontent.com/198639/117480597-b810f000-af59-11eb-87a2-66623544b59b.png)

- 👍Reasonably simple to implement
- 👍Familiar
- ❌No native Qt element
- ❌Either always visible (but inactive) or causes model selection box to resize as it pops in/out.

# Infinite progress bar beneath the translation output text box
![progressbar](https://user-images.githubusercontent.com/198639/117479356-248aef80-af58-11eb-86e0-92053e463a0a.png)

- 👍Very simple to implement
- ❌Location not very intuitive
- ❌I don't find infinite progress bars very intuitive
- ❌Changes window size (or text box size) when it shows/hides

## Infinite progress bar in window status bar
![statusbar](https://user-images.githubusercontent.com/198639/117480984-3d94a000-af5a-11eb-8490-9963682af765.png)

- 👍Very simple to implement
- 👍Familiar (albeit very old fashioned)
- 🤔Space for future controls (maybe a grid mode switch for mass translation?)

## Animated ellipsis at the end of the translated text in the output text box.
![elllipsis](https://user-images.githubusercontent.com/198639/117479354-2359c280-af58-11eb-9074-d5779d05feae.png)
([inspiration](https://www.cssscript.com/demo/12-pure-cssscss-loading-indicators-spinthatshit/))

- 👍Fancy
- ❌Relatively hard to implement
- ❌What to do when there's more text than fits in the output box? Does indicator scroll out of view?

**Comment by XapaJIaMnu** [comment]
While we are it, we should add some label that displays the translation speed, without being overly cluttered. Ideas for location. Therefore I like `Infinite progress bar in window status bar`

Finally, I was told that it is difficult to find languages. It might not be so much of an issue now, but it will become a much bigger issue when we have more models. I think that having a something like opus interface where we select from (language) and to language in two separate drop down menus would work. 

What do you think?

**Comment by jelmervdl** [comment]
I think I agree with using the status bar for a busy indicator. It's also a logical place for translation speed: nicely groups all the status indicators together.

About the model drop down, yes, I agree that this current implementation will become pretty annoying as soon as there's something like 10 more options added. I'll make another ticket for that and some ideas. #14

**Comment by jelmervdl** [comment]
Forgot to add: I'd be happy to add the status bar and activity indicator

**Comment by XapaJIaMnu** [comment]
Yes, could you do the status bar and activity? Afterwards we can experiment with some indicator about translation speed.

**Comment by jelmervdl** [comment]
Implemented through #15.
