### ISSUE TITLE
Ability to load firefox-translations-models

### ISSUE THREAD

**Issue by c6401** [XapaJIaMnu/translateLocally#134]
Wondering if I can load some of models from https://github.com/mozilla/firefox-translations-models ?

**Comment by Godnoken** [comment]
Yes, it is possible :)

Let's say you want the Dutch - English model.

1. Create a folder called `nlen.student.tiny` in User/>Your username</Appdata/Roaming/translateLocally
2. Download the files [here](https://github.com/mozilla/firefox-translations-models/tree/main/models/dev/nlen)
3. Unpack each file to your new folder
4. Create a file called `model_info.json` and copy & paste this text;

```
{
  "modelName": "Dutch-English tiny",
  "shortName": "nl-en-tiny",
  "type":      "tiny",
  "src":       "Dutch",
  "trg":       "English",
  "srcTags":   {"nl": "Dutch"},
  "trgTag":    "en",
  "repository": "Bergamot",
  "version":   1,
  "API":       1
}
```

5. Create a file called `config.intgemm8bitalpha.yml` and copy & paste this text;

```
relative-paths: true
models:
  - model.nlen.intgemm.alphas.bin
vocabs:
  - vocab.nlen.spm
  - vocab.nlen.spm
shortlist:
    - lex.50.50.nlen.s2t.bin
    - false
beam-size: 1
normalize: 1.0
word-penalty: 0
mini-batch: 64
maxi-batch: 1000
maxi-batch-sort: src
workspace: 2000
max-length-factor: 2.0
skip-cost: true
gemm-precision: int8shiftAlphaAll
```

6. You should now be able to see it in the translateLocally app

That's it. Basically you just have to adjust each of their models to fit into translateLocally's format.
Keep in mind that you'll have to rename some lines in these two files to adjust for other languages. Some models may also have two vocab files, one for source and one for target.

**Comment by c6401** [comment]
Awesome, thank you!

**Comment by c6401** [comment]
the solution works brillliantly
