### ISSUE TITLE
Crash with SIGABRT on translation attempt

### ISSUE THREAD

**Issue by pacien** [XapaJIaMnu/translateLocally#140]
Context: I'm trying to create a distro package of this program for NixOS.
(https://github.com/NixOS/nixpkgs/pull/251051).

The CLI and GUI start and are able to donwload models.

However, attempting a translation results in a crash with SIGABRT.
This is happening both with and without MKL, and both on CLI and in GUI.

Platform info: NixOS 23.05 (Linux 6.1 LTS, x86_64).
translateLocally commit: 9f3195.

```fish
❯ nix build github:NixOS/nixpkgs/f906ee5bf2816bd9817a86355051339d84bdfaff#translate-locally
# built output is placed in ./result

❯ ./result/bin/translateLocally -d en-fr-tiny
Downloading English-French type tiny...
100% [############################################################]
Model downloaded successfully! You can now invoke it with -m en-fr-tiny

❯ echo "hello world" | ./result/bin/translateLocally -m en-fr-tiny
fish: Process 516219, './result/bin/translateLocally' from job 1, 'echo "hello world" | ./result/b…' terminated by signal SIGABRT (Abort)
```

Using the `--debug` flag does not give any additional info.

**Comment by XapaJIaMnu** [comment]
Did you have mkl installed before compiling? Most likely it was compiled without compatible Blas library. We should make it hard fail in this case.

**Comment by pacien** [comment]
Quoting Nikolay Bogoychev (2023-08-24 00:33:50)
> Did you have mkl installed before compiling? Most likely it was compiled
> without compatible Blas library. We should make it hard fail in this case.

I'm producing two versions of the package: one with mkl and one without.
Both are compiling fine, but both are crashing when translating.
I also tried to add Blas (version 3) as dependency for both, but same crash.

**Comment by XapaJIaMnu** [comment]
During compilation do you have something like "found mkl" in the cmake log?

**Comment by pacien** [comment]
Quoting Nikolay Bogoychev (2023-08-24 01:02:16)
> During compilation do you have something like "found mkl" in the cmake log?

CMake seems to be able to find all the other dependencies automatically,
but not BLAS, CBLAS, and MKL, even though they are available at the standard
include paths.

I see that there are some custom FindCBLAS.cmake and FindMKL.cmake in the
submodules specifically for that. Is there a way to bypass those?

**Comment by pacien** [comment]
This seems to be enough to fix the BLAS and CBLAS discovery:

  cmakeFlags = [
    "-DBLAS_LIBRARIES=-lblas"
    "-DCBLAS_LIBRARIES=-lcblas"
  ];

However, setting $MKLROOT does not seem to be enough for it to find MKL.

**Comment by XapaJIaMnu** [comment]
What is nix OS mkl package directory structure? Also, we are only looking for static mkl, could it be nix only installs the shared libraries, as opposed to the the static ones?

**Comment by pacien** [comment]
Quoting Nikolay Bogoychev (2023-08-24 08:14:37)
> What is nix OS mkl package directory structure?

Tree: https://gist.github.com/pacien/9ab4b7b6b2b08a38b589ac61b84f1a16

> Also, we are only looking for static mkl, could it be nix only installs
> the shared libraries, as opposed to the the static ones? 

That was indeed the issue!
There are some troubles with the static output of the mkl package.

Nevertheless, the program works well already without mkl,
so that's not blocking; I'll close this issue.

Thank you very much for the help!

**Comment by Vilhelm-Ian** [comment]
I have the same issue. I built it from source. I am using manjaro
