### ISSUE TITLE
Change shared directory path

### ISSUE THREAD

**Issue by XapaJIaMnu** [XapaJIaMnu/translateLocally#151]
Hi @pacien 
Apologies for not noticing this earlier, but in fact not all of our models are Bergamot models.

Could we change this https://github.com/XapaJIaMnu/translateLocally/blob/master/src/inventory/ModelManager.cpp#L518

To translateLocally/models, or something similar? I am asking you, because i know that you package things upstream. Possibly we can just keep this is a backup search location for models.

Cheers,
Nick

**Comment by pacien** [comment]
I've opened a PR to change that path to XDG_DATA_DIRS/translateLocally/models.
See #152.

The downstream PR for the models hasn't yet been merged,
so there is no need to look in both directories.
