### ISSUE TITLE
Ubuntu 20,04: Always "Illegal instruction (core dumped)"

### ISSUE THREAD

**Issue by dlippold** [XapaJIaMnu/translateLocally#156]
I have a new installed and updated Ununtu 20.04 system. Here are some information about that:

`uname -prsv`

> Linux 5.4.0-166-generic #183-Ubuntu SMP Mon Oct 2 11:28:33 UTC 2023 x86_64

`cat /etc/os-release`

> NAME="Ubuntu"
> VERSION="20.04.6 LTS (Focal Fossa)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 20.04.6 LTS"
> VERSION_ID="20.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=focal
> UBUNTU_CODENAME=focal

I have downloaded and installed (by using apt-get) the file `https://translatelocally.com/files/latest/translateLocally-Ubuntu-20.04.deb`

When I now execute `translateLocally -v` or `translateLocally -l` I get:

> Illegal instruction (core dumped)

What can I do to investigate the problem?

**Comment by kpu** [comment]
What is your CPU?  `cat /proc/cpuinfo`

**Comment by dlippold** [comment]
Its a virtual system. Output of `cat /proc/cpuinfo` is 6 times something link the following.

> processor       : 0
> vendor_id       : AuthenticAMD
> cpu family      : 15
> model           : 107
> model name      : QEMU Virtual CPU version 2.5+
> stepping        : 1
> microcode       : 0x1000065
> cpu MHz         : 1996.250
> cache size      : 512 KB
> physical id     : 0
> siblings        : 6
> core id         : 0
> cpu cores       : 6
> apicid          : 0
> initial apicid  : 0
> fpu             : yes
> fpu_exception   : yes
> cpuid level     : 13
> wp              : yes
> flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm rep_good nopl cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 x2apic popcnt aes xsave rdrand hypervisor lahf_lm cmp_legacy abm 3dnowprefetch ssbd ibpb vmmcall arch_capabilities
> bugs            : fxsave_leak sysret_ss_attrs null_seg swapgs_fence amd_e400 spectre_v1 spectre_v2
> bogomips        : 3992.50
> TLB size        : 1024 4K pages
> clflush size    : 64
> cache_alignment : 64
> address sizes   : 40 bits physical, 48 bits virtual
> power management:

I have attached the full output.
[cpuinfo.txt](https://github.com/XapaJIaMnu/translateLocally/files/13245857/cpuinfo.txt)

**Comment by XapaJIaMnu** [comment]
The minimum binary that we put on the website requires avx which you do not have.

You can however download the x86 release and that should work for you: https://github.com/XapaJIaMnu/translateLocally/releases/download/latest/translateLocally-v0.0.2+3cbe86d-Ubuntu-20.04.x86-64.deb

**Comment by dlippold** [comment]
Thanks for the explanation and the link. That version works fine. Is that version newer than the version _20.04 LTS compat_ from the download page (i.e. https://translatelocally.com/files/latest/translateLocally-Ubuntu-20.04.compat.deb)? Now I tried also that version and it works too.

**Comment by XapaJIaMnu** [comment]
Yes, the compat version is the same as the `x86_64` release which doesn't rely on avx instructions.
