### ISSUE TITLE
Currently no models can be downloaded

### ISSUE THREAD

**Issue by dlippold** [XapaJIaMnu/translateLocally#159]
Since some hours there is a certificate problem with the web server https://data.statmt.org (it seems to me that a new certificate was installed). Therefore it is currently not possible for translateLocally to download model files.

**Comment by XapaJIaMnu** [comment]
We're upgrading our Web server, it should be a few days until things settle down, sorry

**Comment by dlippold** [comment]
The problem no longer occurs.
