### ISSUE TITLE
Mistranslation

### ISSUE THREAD

**Issue by zenlan** [XapaJIaMnu/translateLocally#172]
Hello, I'm wondering about this translation...
![image](https://github.com/user-attachments/assets/3f797180-8500-42b8-a5dc-67ac39772b53)
It should be...
![image](https://github.com/user-attachments/assets/88667824-07d0-4a9b-b0aa-bca740cb442b)
Not exactly an urgent issue although I would like to be sure that when automating thousands of local translations I won't be releasing random unsolicited rude words into my datasets! :D Thanks!

**Comment by zenlan** [comment]
Apologies if this is not the place to raise issues about individual translations or models, please point me to wherever is more appropriate.

But here is another one...
![image](https://github.com/user-attachments/assets/1fc9c6b4-0dc8-46f8-a9c9-21689d822a97)

**Comment by XapaJIaMnu** [comment]
Hi Zenlan,

These are unfortunately known issues with this current model, and we can't really do anything about it without retraining it. AFAIK Mozilla are still working on this and trying to fix those, but idk if they have released a new model.

They used to take bug reports here: https://github.com/mozilla/firefox-translations/issues?q=is%3Aissue+is%3Aclosed, but now they've moved to their bugzilla: https://github.com/mozilla/firefox-translations/issues/737

Sorry about that!

Nick
