### ISSUE TITLE
Loading time is really slow

### ISSUE THREAD

**Issue by XapaJIaMnu** [XapaJIaMnu/translateLocally#19]
We are still loading the model N times, once for each core. We should backport the work of @graemenail backported to the browsermt branch of marian.

**Comment by graemenail** [comment]
I'm waiting for a review on marian-dev. Do you want me to open a PR on browsermt?

**Comment by XapaJIaMnu** [comment]
Yes please! Pull request spend a long time on hold against master, sadly.

**Comment by graemenail** [comment]
PR is merged. Hopefully improves loading times

**Comment by XapaJIaMnu** [comment]
Yes, this is now fixed, thank you very much @graemenail !
