### ISSUE TITLE
Change the way VERSION is parsed

### ISSUE THREAD

**Issue by XapaJIaMnu** [XapaJIaMnu/translateLocally#20]
For some reason, on mac, if you have boost installed via homebrew, compilation will fail unless the file `VERSION` is removed. Investigate and fix.

**Comment by XapaJIaMnu** [comment]
Some improvements have happened, at least for now there is a clean compilation on mac.

**Comment by jelmervdl** [comment]
I no longer have any issues building on mac. As far as I'm concerned this issue is fixed.

**Comment by XapaJIaMnu** [comment]
I want to change it a bit so that it gets baked into the executable

**Comment by XapaJIaMnu** [comment]
@jelmervdl should we close this now?
