### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by kpu** [XapaJIaMnu/translateLocally#21]
Models appear to be downloaded over HTTP without some form of validation.  
http://data.statmt.org/bergamot/models/models.json
One can overwrite arbitrary files with a Marian configuration.  
We could ship checksums as metadata or enable HTTPS properly.

**Comment by XapaJIaMnu** [comment]
I can add a checksum to the json, I guess. Why does data.statmt.org not have https version?

**Comment by jelmervdl** [comment]
Would it make sense to host the models.json file somewhere on Github? That would give us stable hosting + https + some way to allow others to contribute models for pretty much free.

If there are checksums for the downloads in the json file, it doesn't matter much where those models come from. They can stay on http-only data.statmt.org or some CDN if they ever become annoying to host.

**Comment by kpu** [comment]
I can host the JSON on https://translatelocally.com/

**Comment by XapaJIaMnu** [comment]
None whatsoever. I don't have access to whoever hosts translateLocally.com so I someone has to manually copy that from the students deployment repo.

**Comment by kpu** [comment]
Updated.

**Comment by XapaJIaMnu** [comment]
The models.json is generated by this script: https://github.com/browsermt/students/blob/master/generate_models_json.py which is called repeatedly by https://github.com/browsermt/students/blob/master/deploy.students.sh
We should incorporate the automatic sha256sum field in there.

**Comment by XapaJIaMnu** [comment]
While this is merged now, I'd like to keep this open until the student repo automatically generates the checksums.

**Comment by jelmervdl** [comment]
I'll make a pull request on the students repo that adds the sha256 checksums.

**Comment by jelmervdl** [comment]
Forgot to tag this issue in the pull request. It's here: https://github.com/browsermt/students/pull/39

**Comment by XapaJIaMnu** [comment]
Fixed by @jelmervdl
