### ISSUE TITLE
Git version parsing doesn't get updated during the first cmake run

### ISSUE THREAD

**Issue by XapaJIaMnu** [XapaJIaMnu/translateLocally#32]
Currently, we store the short github hash into a cmake variable:
https://github.com/XapaJIaMnu/translateLocally/blob/44a1148ee826abf2d7de453817a6d0eef55fad71/cmake/GetVersionFromFile.cmake#L26

However this doesn't seem to be updated during the first cmake run. IE if you run `cmake ..` on a clean directory you would see.
```bash
...
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Building translateLocally-v0.0.1+
-- Found LibArchive: /usr/lib/x86_64-linux-gnu/libarchive.so (found version "3.2.2") 
-- Looking for C++ include pthread.h
...
```
Whereas a second `cmake ..` run would display
```bash
Building translateLocally-v0.0.1+44a1148
-- Submodule update
```
I am not sure why this is not working.

**Comment by jelmervdl** [comment]
`GIT_EXECUTABLE` is empty the first time cmake is executed.

I added `COMMAND_ECHO STDERR` to the `execute_process(COMMAND ${GIT_EXECUTABLE} rev-parse --short HEAD ...)` line and the first time it shows `'rev-parse' '--short' 'HEAD'`. Re-running cmake it shows `'/usr/bin/git' 'rev-parse' '--short' 'HEAD'`.

It might be set as a CACHE variable by one of the subprojects? Related: all subprojects take on the git hash from the translatelocally project into their version string, not their own hashes:
```
Building translateLocally-v0.0.1+d681ab4
-- Submodule update
CMake Warning at 3rd_party/bergamot-translator/CMakeLists.txt:20 (message):
  CMAKE_BUILD_TYPE not set; setting to Release


-- Submodule update
-- Project name: bergamot_translator
-- Project version: v0.3.1+d681ab4
-- Project name: marian
-- Project version: v1.9.56+d681ab4
...
```

**Comment by XapaJIaMnu** [comment]
Yeah, i see. This is used by marian. That would be the issue.

**Comment by jelmervdl** [comment]
This is probably either intentional in marian, or a bug over there, for choosing to use `CMAKE_SOURCE_DIR` instead of `CMAKE_CURRENT_SOURCE_DIR` in their `GetVersionFromFile.cmake` script.

**Comment by XapaJIaMnu** [comment]
We should do PRs on the submodules to fix that. I assume this bug is safe to close in the meantime?
