### ISSUE TITLE
Placeholder text not readable on macOS with Dark mode enabled

### ISSUE THREAD

**Issue by jelmervdl** [XapaJIaMnu/translateLocally#40]
With dark mode enabled on macOS the placeholder text cannot be read.
![image](https://user-images.githubusercontent.com/198639/120243204-e20ab900-c25e-11eb-859e-f91e315f5843.png)

**Comment by jelmervdl** [comment]
Seems to be a Qt6 issue: https://bugreports.qt.io/browse/QTBUG-89984

**Comment by XapaJIaMnu** [comment]
I guess this is minor enough that we can ignore it until they fix it in upstream?

**Comment by jelmervdl** [comment]
I tried to patch it: https://github.com/XapaJIaMnu/translateLocally/compare/master...jelmervdl:macos-dark-mode-fix

… But it doesn't update properly yet when the OS changes between light & dark mode while the rest of the interface does. It also seems very easy to fix on Qt's side. They just missed this theme property in their Cocoa theme plugin for some reason. So let's hope upstream will figure it out quickly.

**Comment by jelmervdl** [comment]
Seems to have been fixed with https://github.com/qt/qtbase/commit/3bb523eb662aaa157c0b6ebd35c5fee515edc082.

It seems to have been back-ported to 6.1.2 because it now works for me with the current version from homebrew: Qt 6.1.2 🙌

**Comment by XapaJIaMnu** [comment]
Binaries need to be rebuilt before closing this.

**Comment by XapaJIaMnu** [comment]
Has this fix been backported to the Qt5 branch? Sadly Qt6 build didn't work with vcpkg 3 weeks ago.

**Comment by XapaJIaMnu** [comment]
I'm talking shit, Macos is built against 6.1.2
