### ISSUE TITLE
One minor bug: the language pair lists appears three times (Ubuntu 20.04.01).

### ISSUE THREAD

**Issue by kpu** [XapaJIaMnu/translateLocally#42]
@mlforcada says "One minor bug: the language pair lists appears three times (Ubuntu 20.04.01)." https://twitter.com/MikelForcada/status/1400537992343834628

**Comment by XapaJIaMnu** [comment]
This happens when statmt is slow to respond and the impatient user clicks "Download models" 3 times. We do not block the button until the download is executed.

**Comment by kpu** [comment]
I need to get round to buying that new webserver :'(.

**Comment by XapaJIaMnu** [comment]
And reconfiguring it with nginx*
