### ISSUE TITLE
Add user-agent header to all network requests

### ISSUE THREAD

**Issue by jelmervdl** [XapaJIaMnu/translateLocally#44]
We should add a User-Agent header to all model list and model download requests so we can get an idea of how many clients of which version are still around, and use that info to know whether we should still host old versions of models in case of an API update.

**Comment by XapaJIaMnu** [comment]
We should be always backwards compatible, even if it is prompting users to update their model on launch. A user starting a new program with the old models already downloaded should be prompted to update and to not crash.

A user downloading new models with old version of the app should be able to at least get a message such as "API unsupported, please upgrade."

**Comment by jelmervdl** [comment]
Implemented in #47
