### ISSUE TITLE
Local model management

### ISSUE THREAD

**Issue by jelmervdl** [XapaJIaMnu/translateLocally#45]
From #34, @XapaJIaMnu mentioned we should have some way to manage local models from the app (without going to a hidden folder)

I suggest adding a table view to the settings pane, as a second tab, where you can see the name of the model, the version number, the total file size, and a button to delete it.

Additionally, how do we expect users to download models if not though the app? Possible options:
1.  Add an "Import model…" menu item that opens a file browser dialog.
2. Add an "Import model…" button below the table in the settings pane that does the same.
3. Drag & drop .tar.gz files onto this table
4. Drag & drop .tar.gz files onto the app window or dock icon (in case of macOS, not sure how other desktop environments normally deal with this)
5. Make up a new file extension, rename all online models with it, and register the app as a viewer for said file extension so you can basically double click to install. Added bonus is that browsers won't automatically try to extract the file after downloading because it's a recognised archive format. (I'm looking at you, Safari…)
6. Just load any model that's in the same directory as the application; imagine having a USB stick with the .exe and a bunch of model directories. Trouble right now is that we need to have extracted archives for models to be loaded.

Will we host models for download through the browser somewhere? For the purpose of having a fully offline installation, this might be good. I assume some page somewhere on translatelocally.com would be the most logical place. Technically, there is also not really a reason to combine a bunch of models into a single .tar.gz and host it as an "English -> Anything starter kit" or something.

**Comment by XapaJIaMnu** [comment]
Hey,

That sounds reasonable, with regards to the model management tab. As for the rest.

1. Are expecting folders or archives? Atm I scan a folder and if a model_info.json appears, it's valid. I scan the current folder, as well as the settings directory.
2. Same as 1
3. Sounds nice, but should we be able to handle folders
4. Same as 3
5. I don't think we should be having a new extension.
6. Already works, as long as the models are extracted. The folder name doesn't matter, as long as it's in the same directory as the .exe/compiled file.

**Comment by XapaJIaMnu** [comment]
Fixed via #48
