### ISSUE TITLE
Show alignment data in translation

### ISSUE THREAD

**Issue by jelmervdl** [XapaJIaMnu/translateLocally#50]
[bergamot-translate exposes alignment information](https://github.com/browsermt/bergamot-translator/blob/main/src/translator/response.h) and it would be cool to expose this in the interface.

I propose we initially use it to sync the visible part in the input and translated text boxes. I.e. make sure the part you're editing in the source text is also visible in the translated text box so you immediately see the results of your editing.

For example, when in Overleaf you click somewhere in the preview document, it will move the cursor in the edit document to the section you clicked. 

A next step (hidden behind a toggle) could be [a sort of focus mode](https://ia.net/writer), where the sentence you're editing is highlighted both in the input text box and the translated text box. (This would be a bit more tricky to implement I expect due to how the sentence boundaries in the input box need to be updated/estimated while you type, not only when translation is available.)

Another example could be what OPUS-CAT does is a synchronised hover effect.
![Screenshot 2021-07-07 at 13 41 43](https://user-images.githubusercontent.com/198639/124761409-ad5ae300-df29-11eb-9058-52fd0ff41054.png)
We could have something similar in one direction by highlighting the word/substrings in the translation that align with the word/substring that currently under/next to the caret in the input text box. For the other (translation -> source text) direction, maybe clicking/selecting a word/substring also selects the aligned parts in the input text box?

**Comment by ChrisBurnsOneOne** [comment]
This is already the intention for the Firefox plugin version. Mozilla should be on the case producing a couple of slightly different prototypes which have been suggested over the last month or so.

**Comment by jelmervdl** [comment]
Oeeh that would be interesting!

**Comment by ChrisBurnsOneOne** [comment]
Unsure how much of it I can share in terms of basic concepts, but I Nikolai should already have seen some of this work. There's no real reason the plugin and desktop versions need to re-invent the wheel here.

**Comment by XapaJIaMnu** [comment]
Closed via #52
