### ISSUE TITLE
Make it usable from the shell

### ISSUE THREAD

**Issue by unhammer** [XapaJIaMnu/translateLocally#51]
I'd love to be able to `echo ikkje så gale | translateLocally nno-eng` (also handy for chaining with other engines like apertium)

**Comment by jelmervdl** [comment]
Oh yes I've been wanting something like this while testing as well.

What would be the expected behaviour? Should it just read stdin till the end to populate the input text box?

**Comment by unhammer** [comment]
It shouldn't open the GUI at all, just print to stdout. Maybe it should require a flag, e.g. `-n/--no-gui` or something:

`$ grep ikkje corpus.txt | translateLocally -n nno-eng | apertium eng-kaz >kaz.txt`

**Comment by kpu** [comment]
Here come the language codes and the inevitable conflict between hyphen for BCP47 and hyphen to delimit language direction.

**Comment by jelmervdl** [comment]
> It shouldn't open the GUI at all, just print to stdout. Maybe it should require a flag, e.g. -n/--no-gui or something:

Basically that would be exactly the same as calling Marian with one of translateLocally's models. The benefit here would be that you don't need to download & install marian separately, and that translateLocally will figure out the command line arguments for you.

> Here come the language codes and the inevitable conflict between hyphen for BCP47 and hyphen to delimit language direction.

That will be a problem if we ever want to support something like translating using a pivot language. I suppose there's no reason to not just pass the two languages as two separate arguments, as opposed to one with a dash.

**Comment by unhammer** [comment]
> I suppose there's no reason to not just pass the two languages as two separate arguments, as opposed to one with a dash.

That would be nice, would make it unambiguous.

**Comment by XapaJIaMnu** [comment]
I have gotten this request from other people as well. How about a noGUI option `-n; --no-gui`;  list models `-l --list-models` (Lists locally installed models and quits) and then `-s --source` that specifies the source language and `-t --target` for the target language?
I would have time to look at this in a few weeks.

**Comment by XapaJIaMnu** [comment]
> On top of this, I want to use the library code to be able to spawn a daemon / service running in the background and loading-unloading models accordingly (we have multimodel support upstream). If this can be hooked via [dbus](https://www.freedesktop.org/wiki/Software/dbus/) to something like [ibus](https://github.com/ibus/ibus), we have system-wide outbound translation - on word documents, browsers, text editors whatever, at least for linux.

As i said before I'm not using the hacky model swapping.  We don't have a usecase for it. For everything else, please open a separate issue with what you want/propose

**Comment by XapaJIaMnu** [comment]
@unhammer  This functionality is now implemented.
