### ISSUE TITLE
Application crashes whenever I translate

### ISSUE THREAD

**Issue by thansk** [XapaJIaMnu/translateLocally#59]
v0.0.2+be52de5

Installed through AUR.

Whenever I launch the application this is the output in the console:

```
QCoreApplication::postEvent: Unexpected null receiver
```

The application shows up and I have downloaded some models. When I enter some text and press on translate, it crashes and `Aborted` gets appended in the terminal.

**Comment by kpu** [comment]
What CPU model do you have?

**Comment by XapaJIaMnu** [comment]
Could you please post  `pacman -Q intel-mkl`
If you don't have MKL installed, could you try installing MKL (`pacman -S intel-mkl`) and rebuilding? I suspect it might an MKL issue.

**Comment by thansk** [comment]
> What CPU model do you have?

Intel

> Could you please post `pacman -Q intel-mkl-static` If you don't have MKL installed, could you try installing MKL (`pacman -S intel-mkl-static`) and rebuilding? I suspect it might an MKL issue.
> 
> EDIT: I have updated the PKGBUILD on AUR.

This fixed it, thanks a lot!
