### ISSUE TITLE
Firewall hangs the GUI indefinitely

### ISSUE THREAD

**Issue by XapaJIaMnu** [XapaJIaMnu/translateLocally#6]
The case when there is no network connection is handed gracefully, but when packages are just dropped, the GUI will hang forever. We should instead detect this situation and prompt the user to allow us through the firewall.

**Comment by XapaJIaMnu** [comment]
Some safeguards added that would fix it on Windows, Mac and newer Linux. Have to retest

**Comment by XapaJIaMnu** [comment]
I think this is fixed now, does anyone have a firewall'd system to check?

**Comment by XapaJIaMnu** [comment]
@jelmervdl I think right now if there is a time out you get something like "Unable to reach server", right?

**Comment by jelmervdl** [comment]
Installed [a firewall GUI](https://murusfirewall.com/scudobeta/index.php) and yes, it just gives you a popup with "Operation canceled" after 10 seconds. After that the option to "download models…" to try again re-appears, as expected.

**Comment by XapaJIaMnu** [comment]
Ubuntu 20.04 sadly still ships with an old qt version that doesn't have proper timeout support https://github.com/XapaJIaMnu/translateLocally/blob/db88f0d571055ae7750a72f35413575e2dad6f6f/src/Network.cpp#L9

I guess ubuntu users are less likely to have firewall troubles anyways?

**Comment by jelmervdl** [comment]
I looked a bit at the original Qt ticket of the feature: https://bugreports.qt.io/browse/QTBUG-3443

There are some backward compatible solutions mentioned, but they're all a bit more involved to implement and I don't think any of them has the exact same behaviour as `setTransferTimeout()`. E.g. [this one](https://gitlab.com/-/snippets/1807769) would interrupts downloads that are making progress while for setTransferTimeout says _Transfers are aborted *if no bytes are transferred* before the timeout expires_.

So probably not worth trying to get right unless someone would actually benefit from a pre 5.15 solution.

**Comment by XapaJIaMnu** [comment]
Yeah, that's the conclusion that I got when I implemented this. Technically, ubuntu users of 20.04 including would, but I as they don't often run super restrictive firewalls, I think that's fine.

Also, do you think 10 seconds is too long? Would 5 be better?

**Comment by jelmervdl** [comment]
I think 10s is good. I feel like less would trigger errors too often due to just weird issues happening en route.
\**looks at his own local network and how DHCP sometimes just… flops.\**

Also let's give @kpu some time to make that webserver respond fast more consistently 😛
