### ISSUE TITLE
If showAlignments is disabled console is spammed with unexpected null receiver

### ISSUE THREAD

**Issue by XapaJIaMnu** [XapaJIaMnu/translateLocally#64]
A `QCoreApplication::postEvent: Unexpected null receiver` warning appears if the showAlignments option is disabled in the settings at the program start. This shouldn't happen and could (maybe?) result in something more nefarious?

**Comment by jelmervdl** [comment]
Yep, that was bad. QPointer here was effectively a nullptr that I called methods on anyway. I'm a bit surprised it didn't just outright segfault…
