### ISSUE TITLE
No Qt platform plugin could be initialized

### ISSUE THREAD

**Issue by maxiek0071** [XapaJIaMnu/translateLocally#65]
Hi everyone,

I have built TranslateLocally as described in Readme.

When I try executing the `./translateLocally --help` in the `/build` repository, I am getting the following error:

```QFactoryLoader::QFactoryLoader() checking directory path "/home/ubuntu/translateLocally/build/platforms" ...
loaded library "/opt/conda/plugins/platforms/libqxcb.so"
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, webgl, xcb.

Aborted
```

I put the ` export QT_DEBUG_PLUGINS=1` command to get the full error log.

Please note that I use Debian GNU/Linux 10 over a ssh connection. There is no display available. I am interested in using Translate Locally over the command line.

Would someone here have an idea of how to execute the Translate Locally from the CLI?

I appreciate your help.

**Comment by XapaJIaMnu** [comment]
So you can use the following workaround: ```xvfb-run --auto-servernum ./translateLocally --version```
We do that for the workflows
https://github.com/XapaJIaMnu/translateLocally/blob/a603422ce19f490bfb8aa888ae12a1c022a75f4c/.github/workflows/ubuntu-all.yml#L68

I am not sure if we can make QT not require X at all, but xvfb should make it usable for the time being?

**Comment by kpu** [comment]
In fairness it does seem bizarre that the command line version requires QT...

**Comment by XapaJIaMnu** [comment]
It's due to the binary being linked to all qt modules statically as opposed to loading them on demand.

**Comment by kpu** [comment]
Does the X version need to be the same executable?

**Comment by maxiek0071** [comment]
Thanks for the answer. Now, I can see the version. -->

```
ubuntu@vm:~/translateLocally/build$ xvfb-run --auto-servernum ./translateLocally --version
translateLocally v0.0.2+a603422
```

How can I download models from the CLI? When I try to translate, it shows the following:
```
ubuntu@vm:~/translateLocally/build$ echo "Me gustaria comprar la casa verde" | xvfb-run --auto-servernum ./translateLocally -m es-en-tiny

We could not find a model identified as: "es-en-tiny" . Use translateLocally -l to list available models or use the GUI to download some from the internet.
```

Here is the list of my models (empty):
```
ubuntu@vm1:~/translateLocally/build$ xvfb-run --auto-servernum ./translateLocally --list-models
```

Thank you for your help.

**Comment by XapaJIaMnu** [comment]
Hey,

We currently do not support downloading models from command line. I will try to add support for that soon.

In the meantime, you can download the models through the GUI on your own machine and then copy them to the target machine via scp.

Models are located in the following directories:
On Linux: `~/.config/translateLocally/`
On Windows: `C:/Users/<USER>/AppData/Local/translateLocally'
Not sure about mac

The models are placed in individual directories. If you copy those directories to the same directory as the executable, they will be picked up.

**Comment by XapaJIaMnu** [comment]
@maxiek0071 Check out #66 it adds first class support for downloading and removing models from the command line.
