### ISSUE TITLE
Command Line interface downloader hangs indefinitely on zisa (suspect race condition)

### ISSUE THREAD

**Issue by XapaJIaMnu** [XapaJIaMnu/translateLocally#77]
Indefinite hang occurs when executing:
```bash
$ QT_QPA_PLATFORM=offscreen translateLocally -d en-de-base
Downloading English-German type base...
100% [############################################################]
```
I suspect download occurs too fast and somehow completes before the event loop that waits for it starts, resulting in an indefinite hang.

Issue is somewhere around these lines:

https://github.com/XapaJIaMnu/translateLocally/blob/94106843d40aeb5d0d190d9366147467b782cd0d/src/CommandLineIface.cpp#L224

I can't reproduce this issue locally or on any other machine I own. Maybe it would be reproducible from the forum.

**Comment by jelmervdl** [comment]
It could also be emitting a `Network::error` signal, which isn't listened to by CommandLineInterface.

**Comment by XapaJIaMnu** [comment]
You're right, it is an error. Unfortunately no idea how to fix it.
