### ISSUE TITLE
force-stop translation on quit

### ISSUE THREAD

**Issue by jelmervdl** [XapaJIaMnu/translateLocally#78]
I just noticed that ctrl+c on the command-line does kill in-flight translation, but Cmd+Q keeps the application alive till translation is finished. It does close the main window though.

To reproduce: select a model, paste in Crime & Punishment, press cmd+q before it finishes translating.

Result: The main window closes immediately, but the application stays active in the foreground and in the dock.

Expected: application closes completely when the main window disappears.

Not sure if there is a way to somehow either signal to bergamot-translator that it is time to stop, or signal the MarianInterface worker that it (and all its "child threads") should just bail. Since they're not separate processes I don't think there is an easy way to achieve this?

**Comment by jerinphilip** [comment]
Something like the following? When the loop exits the threads should be joinable faster than after consuming the whole data. 

<details>
<summary>Click to expand and see diff </summary>

```diff
diff --git a/src/translator/service.cpp b/src/translator/service.cpp
index 8acbc97..f0be344 100644
--- a/src/translator/service.cpp
+++ b/src/translator/service.cpp
@@ -54,13 +54,15 @@ AsyncService::AsyncService(const AsyncService::Config &config)
       // shutdown, which happens in the destructor for this class.
       Batch batch;
       Ptr<TranslationModel> translationModel{nullptr};
-      while (safeBatchingPool_.generateBatch(translationModel, batch)) {
+      while (safeBatchingPool_.generateBatch(translationModel, batch) && !forceQuit_) {
         translationModel->translateBatch(cpuId, batch);
       }
     });
   }
 }

+void AsyncService::forceQuit() { forceQuit_ = true; }
+
 AsyncService::~AsyncService() {
   safeBatchingPool_.shutdown();
   for (std::thread &worker : workers_) {
diff --git a/src/translator/service.h b/src/translator/service.h
index e01156a..60458fb 100644
--- a/src/translator/service.h
+++ b/src/translator/service.h
@@ -135,6 +135,8 @@ class AsyncService {

   TranslationCache::Stats cacheStats() { return cache_.stats(); }

+  void forceQuit();
+
  private:
   AsyncService::Config config_;

@@ -155,6 +157,8 @@ class AsyncService {
   // Logger which shuts down cleanly with service.
   Logger logger_;
   TranslationCache cache_;
+
+  std::atomic<bool> forceQuit_{false};
 };

 }  // namespace bergamot
```
</details>

(Ref: https://stackoverflow.com/a/49892649/4565794)

**Comment by jelmervdl** [comment]
You'd also need to call shutdown on the batching pool otherwise it will just be blocking on that and not bother checking forceQuit. And thinking about `safeBatchingPool`, wouldn't calling `shutdown()` on that have the same effect? Workers would quit. It might be enough.

I haven't look at which destructors get called when when you quit the application. E.g. does something maintain a reference to the service when I press quit? Does MarianInterface gets freed? Or does it just receive a "I want to destroy you" signal from the parent but not process it because it is blocking on the translation (MarianInterface blocks on a future it makes for a pending translation, so I would need to work around that at least)

**Comment by jerinphilip** [comment]
I think the delay is from enqueued sentences awaiting translation. Otherwise the destructor of Service already calls `shutdown()`. The `forceQuit_` flag is intended to allow exiting even while stuff is awaiting translation, which won't happen in the `shutdown()` case? 

I have only run tests to check nothing existing is breaking, so I don't know if the solution works. Chances are you can tinker with the above-marked places (just trying to help here by marking the possible places with the diff) and get something to work in translateLocally.

**Comment by jelmervdl** [comment]
@jerinphilip could you add something like this to bergamot-translator?

```diff
diff --git a/src/translator/threadsafe_batching_pool.cpp b/src/translator/threadsafe_batching_pool.cpp
index 0c0d8d85a136f75602e48e9c3033592c8c3497a0..84980a589ef688c31c330d9310431a9c892cec9c 100644
--- a/src/translator/threadsafe_batching_pool.cpp
+++ b/src/translator/threadsafe_batching_pool.cpp
@@ -39,6 +39,7 @@ template <class... Args>
 size_t ThreadsafeBatchingPool<BatchingPoolType>::generateBatch(Args &&... args) {
   std::unique_lock<std::mutex> lock(mutex_);
   work_.wait(lock, [this]() { return enqueued_ || shutdown_; });
+  if (shutdown_) return 0;
   size_t sentencesInBatch = backend_.generateBatch(std::forward<Args>(args)...);
   assert(sentencesInBatch > 0 || shutdown_);
   enqueued_ -= sentencesInBatch;
```

This will make sure that generateBatch() will be falsy when the AsyncService is being shut down. With that in place, it's enough to just release the AsyncService to trigger a shutdown without having to wait for the rest of the sentences.
