### ISSUE TITLE
Model marketplace / add own models feature

### ISSUE THREAD

**Issue by kpu** [XapaJIaMnu/translateLocally#84]
Currently we have a hardcoded JSON path, which keeps things simple.  Users can also add models to the local directory.  

But there are models from other groups like OPUS-MT and seemingly Philipp Koehn is also making some, where they want it to be in the app.  Also we might build models for a specific domain / usecase that are not worth putting in the public app.  Arguably we want the models with an attribution to the group that made them.  Shouldn't have to fork the code to do so: https://github.com/Helsinki-NLP/OPUS-MT-app

Seems the thing to do here is support multiple sources of JSON file.  Maybe we make it a different file type so people can download the file and have the OS launch the app.  Let users add another source to the application.  Eventually we'll want a site with a quality display etc.

**Comment by XapaJIaMnu** [comment]
I will add "repository" functionality and the ability of users to add their own repositories. 

We should also talk to interested parties such as OPUS-MT and Philipp Koehn and have some sort of stakeholder board meeting at some point.

**Comment by kpu** [comment]
Oh I agree there's a need for a stakeholder board meeting. . .

**Comment by XapaJIaMnu** [comment]
@jorgtied would the added functionality work for you to distribute your own models?

**Comment by kpu** [comment]
Own models is an agenda item for Marian stakeholders that I invited @jorgtied to: https://doodle.com/poll/br4dk2zghbrt7d2k
