### ISSUE TITLE
All github runners should produce a package and upload it to a rolling release

### ISSUE THREAD

**Issue by XapaJIaMnu** [XapaJIaMnu/translateLocally#9]
What the title says.

**Comment by XapaJIaMnu** [comment]
https://github.com/XapaJIaMnu/translateLocally/blob/dbaacbfe2a62dfdb2efd0519f5b5b876a285342f/.github/workflows/ubuntu-all.yml#L84
Some progress. Packages are uploaded, but only the workflow that finishes last  gets to keep its package https://github.com/marvinpinto/actions/issues/177

**Comment by jelmervdl** [comment]
I believe you've got this working when #72 was merged.
